### ISSUE TITLE
TARS can display active task list -- advanced

### ISSUE THREAD

**Issue by oman4** [oman4/byu-ee-shop-TARS#8]
There are a few improvements over the basic display functionality that would be nice to have. TARS should be able to:

- [ ] Sort tasks for display according to due date
- [ ] Sort tasks according to priority
- [ ] Give the user the option to display all public active tasks or just tasks assigned to the user
- [ ] Give administrators the option to display all public active tasks, just tasks assigned to the administrator, or tasks assigned to a particular user
