### ISSUE TITLE
TARS can filter active task list

### ISSUE THREAD

**Issue by oman4** [oman4/byu-ee-shop-TARS#9]
It would be nice if users could ask TARS to filter the tasks that it displays to them in response to a /list command. TARS should be able to:

- [ ] Filter tasks according to priority
- [ ] Filter tasks according to whether their due date falls within a certain range of dates
- [ ] Filter tasks according to the users assigned to it
